name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: echo os info
      run: |
        uname -a
        cat /etc/os-release
        free -m
        df -h
    
    - name: build image
      run: |
        printf 'in dev mode, building images'
        docker build -t industryessentials/ymir-backend:release-2.1.0   --build-arg PIP_SOURCE=https://pypi.mirrors.ustc.edu.cn/simple https://github.com/IndustryEssentials/ymir.git#master:/ymir -f Dockerfile.backend
        docker build -t industryessentials/ymir-web:release-2.1.0  --build-arg NPM_REGISTRY=https://registry.npmmirror.com  https://github.com/IndustryEssentials/ymir.git#master:/ymir/web

    - name: save images 
      run: |
        docker save industryessentials/ymir-backend:release-2.1.0 > ymir-backend.tar
        docker save industryessentials/ymir-web:release-2.1.0 > ymir-web.tar
      
    - name: upload images to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ymir-backend.tar
        asset_name: ymir-backend.tar
        tag: release-2.1.0
        overwrite: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
