name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: echo os info
      run: |
        uname -a
        cat /etc/os-release
        free -m
        df -h
    
    - name: build image
      run: |
        DEV_SOURCE_BACKEND_PIP='https://pypi.mirrors.ustc.edu.cn/simple'
        DEV_SOURCE_WEB_NPM='https://registry.npmmirror.com
        printf 'in dev mode, building images'
        docker build -t industryessentials/ymir-backend:release-2.1.0   --build-arg PIP_SOURCE=${DEV_SOURCE_BACKEND_PIP} https://github.com/IndustryEssentials/ymir.git#master:/ymir -f Dockerfile.backend
        docker build -t industryessentials/ymir-web:release-2.1.0  --build-arg NPM_REGISTRY=${DEV_SOURCE_WEB_NPM}  https://github.com/IndustryEssentials/ymir.git#master:/ymir/web

    - name: save images 
      run: |
        docker save industryessentials/ymir-backend:release-2.1.0 > ymir-backend.tar
        docker save industryessentials/ymir-web:release-2.1.0 > ymir-web.tar
      
    - name: upload images
      uses: actions/upload-artifact@v2
      with:
        name: ymir-images
        path: |
          ymir-backend.tar
          ymir-web.tar
