name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    
    - name: build image
      run: |
        docker build -t industryessentials/ymir-backend:release-2.1.0    https://github.com/lszxyz/ymir.git#master:/ymir -f Dockerfile.backend

    - name: save images 
      run: |
        docker save  industryessentials/ymir-backend:release-2.1.0 > ymir-backend.tar
      
    - name: upload images
      uses: actions/upload-artifact@v3
      with:
        name: ymir-images
        path: |
          ymir-backend.tar
