name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

#  build image
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: Jimver/cuda-toolkit@v0.2.11
      id: cuda-toolkit
      with:
        cuda: '11.2.0'

    - run: echo "Installed cuda version is: ${{steps.cuda-toolkit.outputs.cuda}}"

    - run: echo "Cuda install location: ${{steps.cuda-toolkit.outputs.CUDA_PATH}}"

    - run: nvcc -V