name: Build Debian KVM Template

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 00:00 UTC 运行 (北京时间 08:00)
  workflow_dispatch: # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-utils virt-builder sshpass

      - name: Build Debian Template
        env:
          SSH_USER: ${{ secrets.KVM_SSH_USER }}
          KVM_HOST: ${{ secrets.KVM_HOST }}
          STATIC_IP: ${{ secrets.STATIC_IP }}  # 可选的静态 IP 地址
          STATIC_NETMASK: ${{ secrets.STATIC_NETMASK }} # 可选的子网掩码
          STATIC_GATEWAY: ${{ secrets.STATIC_GATEWAY }} # 可选的网关
          STATIC_DNS: ${{ secrets.STATIC_DNS }} # 可选的 DNS 服务器
        run: |
          chmod +x scripts/build_debian_template.sh
          scripts/build_debian_template.sh

      - name: Cleanup
        run: |
          echo "构建完成，清理工作区"