name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: echo os info
      run: |
        uname -a
        cat /etc/os-release
        free -m
        df -h
    
    - name: run redis
      run: |
        docker run -d --name redis -p 6379:6379 redis
      
    - name: test redis performance
      run: |
        docker run --rm --link redis:redis redis redis-benchmark -h redis -c 100 -n 100000 -q

