name: Compression Tool Comparison

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  compression_test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Compression Tools
      run: |
        sudo apt-get update
        sudo apt-get install -y gzip pigz zstd
        
    - name: Clean Up Test Files
      run: |
        # Remove any existing test files
        rm -f 1gb_file.txt 1gb_file.txt.gz 1mb_file.txt 1mb_file.txt.gz 1gb_file.pigz 1mb_file.pigz 1gb_file.zst 1mb_file.zst
        
    - name: Generate Test Files
      run: |
        # Generate 1GB test file
        dd if=/dev/urandom of=1gb_file.txt bs=1M count=1024
        
        # Generate 1MB test file
        dd if=/dev/urandom of=1mb_file.txt bs=1M count=1
        
    - name: GZIP Compression and Decompression
      run: |
        echo "GZIP Compression and Decompression:"
        
        # Compress 1GB file
        time gzip -c 1gb_file.txt > 1gb_file.txt.gz
        
        # Decompress 1GB file
        time gzip -d 1gb_file.txt.gz
        
        # Compress 1MB file  
        time gzip -c 1mb_file.txt > 1mb_file.txt.gz
        
        # Decompress 1MB file
        time gzip -d 1mb_file.txt.gz
        
    # ... (other compression tools)
        
    - name: Output Summary
      run: |
        echo "===== Compression Tool Comparison ====="
        echo "GZIP:"
        echo "- 1GB file compression time: "
        gzip -c 1gb_file.txt | wc -c
        echo "- 1GB file decompression time: "
        gzip -d 1gb_file.txt.gz | wc -c
        echo "- 1MB file compression time: "
        gzip -c 1mb_file.txt | wc -c
        echo "- 1MB file decompression time: "
        gzip -d 1mb_file.txt.gz | wc -c
        
        # ... (other compression tools)
