name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

#  build image
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: 
          git clone https://github.com/modelai/ymir-executor-fork -b ymir-dev
          cd ymir-executor-fork/det-demo-tmi
          docker build -t ymir/executor:det-demo-tmi .
      - name: run the Docker image
        run: docker run -it ymir/executor:det-demo-tmi




